if keyboard_check_pressed(69)
{
	if(chave=1)
	{
		global.chave1=true;
		instance_destroy();
		audio_play_sound(snd_pedestal,3,false,1,0,2);
	}
	if(chave=2)
	{
		global.chave2=true;
		instance_destroy();
		audio_play_sound(snd_pedestal,3,false,1,0,2);
	}
	if(chave=3)
	{
		global.chave3=true;
		instance_destroy();
		audio_play_sound(snd_pedestal,3,false,1,0,2);
	}
	if(chave=4)
	{
		global.chave4=true;
		instance_destroy();
		audio_play_sound(snd_pedestal,3,false,1,0,2);
	}
}